sudo: false
language: r
cache: packages

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get jags
  - sudo apt-get install r-cran-rjags

r_binary_packages: 
  - rjags

r:
  - release
  - devel
